config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :students

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :students, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :category
  validates :name, length: { minimum: 3 }, presence: true
  validates :memo, length: { minimum: 3 }, presence: true
  validates :category_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  decorates_assigned :student, :students
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render 'new'
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def index
    @students = Student.all
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name, :memo, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <% if @student.errors.any? %>
  <div id = "error_explanation" style="color:red;">
    <h2><%= pluralize(@student.errors.count, "error") %>
    prohibited
    this student from being saved:</h2>
  </div>
  <% end %>
	<p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
    <%= student.errormessage(:name) %>
  </p>

	<p>
    <%= f.label :memo %> <br>
    <%= f.text_area :memo %>
    <%= student.errormessage(:memo) %>

  <p>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all , :id, :status, include_blank: true %>
    <%= student.errormessage(:category_id) %>
  </p>

  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/edit.html.erb
<h1> Editing student info </h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
	<tr>
    <th>Name</th>
    <th>memo</th>
    <th>status</th>
    <th colspan='3'></th>
  </tr>

	<% @students.each do |t| %>
    <tr>
      <th><%= t.name %></th>
      <th><%= t.memo %></th>
      <th><%= t.category.status %></th>
      <th><%= link_to 'Show', student_path(t) %></th>
      <th><%= link_to 'Edit', edit_student_path(t) %></th>
      <th><%= link_to 'Destroy', student_path(t),
          method: :delete, data: { confirm: 'Are you sure?' } %></th>
    </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<h1>新規学生登録</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
	<strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @student.memo %>
</p>

<p>
  <strong>Category:</strong>
  <%= @student.category.status %>
</p>

<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<h1>Hello, world!</h1>